from __future__ import annotations

from typing import TYPE_CHECKING

from BaseClasses import Item, ItemClassification, Location

if TYPE_CHECKING:
    from .world import RNGdleWorld


LOCATION_NAME_TO_ID = {
    #uncommon
    "Sandwich": 1,
    "Equilibrium": 2,
    "Semi-Clean": 3,
    "Clean": 4,
    "Harshad Number": 5,
    "Eleven": 6,
    "Five Digits": 7,
    "Canyon": 8,
    "Dozen": 9,
    "Trinity": 10,
    "Prime Number": 11,
    "Mesa": 12,
    "2 Consecutive Numbers(Nearby)": 13,
    "2 Consecutive Numbers(Contains)": 14,
    "Sequence": 15,
    "Rhyme": 16,
    "Balanced": 17,
    "Eighty-Six": 18,
    "Six-Seven": 19,
    "Meaning Of Life": 20,
    "Nice": 21,
    "Snake Eyes": 22,
    "Pocket Mirror": 23,
    "Full House": 24,
    "Blackjack": 25,
    "Feather": 26,
    "Deep Void": 27,
    "Contiguous Trips": 28,
    "Flush": 29,
    "Alternator": 30,
    "Mini Echo": 31,
    "Contiguous Two Pair": 32,
    "Valley": 33,
    "High Roller": 34,
    "Double Hop": 35,
    "Mountain": 36,
    "Low Ball": 37,
    "Equation": 38,
    "Four Of A Kind": 39,
    #rare
    "Three Quarter Century": 40,
    "Semi Century": 41,
    "Quarter Century": 42,
    "Double Nine": 43,
    "Century": 44,
    "Mirror Bookends": 45,
    "Bookends": 46,
    "Three Pair": 47,
    "Four Digits": 48,
    "Paired Bookends": 49,
    "Slopes": 50,
    "Framed Double": 51,
    "Metronome": 52,
    "Steps": 53,
    "Duality": 54,
    "Scramble": 55,
    "Divisible By Three": 56,
    "Calendar": 57,
    "E Slice (3)": 58,
    "Pi Slice (3)": 59,
    "Emergency": 60,
    "Botanist": 61,
    "Orientation": 62,
    "Error 404": 63,
    "Sequence (4)": 64,
    "Devil": 65,
    "Jackpot": 66,
    "Contiguous Full House": 67,
    "Heavy": 68,
    "Secret Agent": 69,
    "Turtle": 70,
    "Deep Void(3)": 71,
    "Contiguous Quads": 72,
    "Palindrome": 73,
    "2 Consecutive Numbers": 74,
    "Firefly": 75,
    "Even Spacing": 76,
    "2nd Power": 77,
    #epic
    "Colossal": 78,
    "Semi-Millenium": 79,
    "Triple Nine": 80,
    "Pronic Number": 81,
    "Millenium": 82,
    "Echo": 83,
    "Three Digits": 84,
    "Decay": 85,
    "Framed Quad": 86,
    "Framed Triple": 87,
    "Framed Pair": 88,
    "Contiguous Three Pair": 89,
    "3 Consecutive Numbers(Contains)": 90,
    "Five Of A Kind": 91,
    "Crescendo": 92,
    "Ascension": 93,
    "Zipper": 94,
    "3 Consecutive Numbers(Scrambled)": 95,
    "Tau Slice(4)": 96,
    "E Slice(4)": 97,
    "Pi Slice(4)": 98,
    "Big Brother": 99,
    "8008": 100,
    "Hell": 101,
    "Leet": 102,
    "6767": 103,
    "Deeper Meaning": 104,
    "Very Nice": 105,
    "Jackpot 4": 106,
    "Straight": 107,
    "Strobogrammatic": 108,
    "Deep Void(4)": 109,
    "Contiguous Fives": 110,
    "Three Consecutive Numbers": 111,
    "3rd Power": 112,
    #anomaly
    "Semi-Epoch": 113,
    "Quad Nine": 114,
    "Epoch": 115,
    "Spy Number": 116,
    "Two Digits": 117,
    "Straight Flush": 118,
    "Binary Soul": 119,
    "Funny Numbers": 120,
    "Homogeneous": 121,
    "4 Consecutive Numbers(Scrambled)": 122,
    "4 Consecutive Numbers(Contains)": 123,
    "Waterfall": 124,
    "4th Power": 125,
    "Fibonacci Number": 126,
    "Cascade": 127,
    "Tau Slice(5)": 128,
    "E Slice(5)": 129,
    "Pi Slice(5)": 130,
    "80085": 131,
    "58008": 132,
    "Royal Flush": 133,
    "Power Of Two": 134,
    "Jackpot Five": 135,
    "Fifth Power": 136,
    "Power Of Three": 137,
    "6th Power": 138,
    #mythic
    "Semi-Eon": 139,
    "Quint Nine": 140,
    "Single Digit": 141,
    "Deep Void(5)": 142,
    "Contiguous Sixes": 143,
    "Eon": 144,
    "Sequence(6)": 145,
    "Hello": 146,
    "Factorial": 147,
    "Power Of Five": 148,
    "Power Of Seven": 149,
    "7th Power": 150,
    "Ouroboros": 151,
    "8th Power": 152,
    "9th Power": 153,
    "4 Consecutive Numbers": 154,
    "Euler's Number": 155,
    "Pi": 156,
    "11th Power": 157,
    "10th Power": 158,
    "Golden Ratio": 159,
    "Tau": 160,
    "19th Power": 161,
    "17th Power": 162,
    "13th Power": 163,
    "Always": 164,
    "Funny Number": 165,
    "Exact Boob": 166,
    "One Million": 167,
    "Full Day": 168,
    "Groundhog Day": 169,
    "Brainrot": 170,
    "Exact Calendar": 171,
    "Exact Orientation": 172,
    "Exact Eighty-Six": 173,
    "Exact Six-Seven": 174,
    "Nine": 175,
    "Eight": 176,
    "Seven": 177,
    "Six": 178,
    "Five": 179,
    "Four": 180,
    "Three": 181,
    "Two": 182,
    "One": 183,
    "Zero": 184,
    "Orwellian": 185,
    "Universal Answer": 186,
    "Mayday": 187,
    "Hotbox": 188,
    "Very Very Nice": 189,
    "17776": 190,
    "Infernal": 191,
    "Not Found": 192,
    "Exact Emergency": 193,
    "Exact Meaning": 194,
    "Exact 80085": 195,
    "Exact Hell": 196,
    "Exact Leet": 197,
    "Exact Devil": 198,
    "Exact Botanist": 199,
    "Jackpot Six": 200,
    "Exact Jackpot": 201,
    "Exact Nice": 202,

    "10k EP": 203, #rare
    "20k EP": 204, #rare
    "30k EP": 205, #epic
    "60k EP": 206, #anomaly
    "100k EP": 207, #anomaly
    "1M EP": 208, #mythic
    "100M EP": 209, #mythic
}

class RNGdleLocation(Location):
    game = "RNGdle"

def get_location_names_with_ids(location_names: list[str]) -> dict[str, int | None]:
    return {location_name: LOCATION_NAME_TO_ID[location_name] for location_name in location_names}

def create_all_locations(world: RNGdleWorld) -> None:
    create_regular_locations(world)
    create_events(world)

def create_regular_locations(world: RNGdleWorld) -> None:
    uncommon = world.get_region("Uncommon")
    rare = world.get_region("Rare")
    epic = world.get_region("Epic")
    anomaly = world.get_region("Anomaly")
    mythic = world.get_region("Mythic")

    region_location_map = {
        uncommon: [
            "Sandwich",
            "Equilibrium",
            "Semi-Clean",
            "Clean",
            "Harshad Number",
            "Eleven",
            "Five Digits",
            "Canyon",
            "Dozen",
            "Trinity",
            "Prime Number",
            "Mesa",
            "2 Consecutive Numbers(Nearby)",
            "2 Consecutive Numbers(Contains)",
            "Sequence",
            "Rhyme",
            "Balanced",
            "Eighty-Six",
            "Six-Seven",
            "Meaning Of Life",
            "Nice",
            "Snake Eyes",
            "Pocket Mirror",
            "Full House",
            "Blackjack",
            "Feather",
            "Deep Void",
            "Contiguous Trips",
            "Flush",
            "Alternator",
            "Mini Echo",
            "Contiguous Two Pair",
            "Valley",
            "High Roller",
            "Double Hop",
            "Mountain",
            "Low Ball",
            "Equation",
            "Four Of A Kind",
        ],
        rare: [
            "Three Quarter Century",
            "Semi Century",
            "Quarter Century",
            "Double Nine",
            "Century",
            "Mirror Bookends",
            "Bookends",
            "Three Pair",
            "Four Digits",
            "Paired Bookends",
            "Slopes",
            "Framed Double",
            "Metronome",
            "Steps",
            "Duality",
            "Scramble",
            "Divisible By Three",
            "Calendar",
            "E Slice (3)",
            "Pi Slice (3)",
            "Emergency",
            "Botanist",
            "Orientation",
            "Error 404",
            "Sequence (4)",
            "Devil",
            "Jackpot",
            "Contiguous Full House",
            "Heavy",
            "Secret Agent",
            "Turtle",
            "Deep Void(3)",
            "Contiguous Quads",
            "Palindrome",
            "2 Consecutive Numbers",
            "Firefly",
            "Even Spacing",
            "2nd Power",
            "10k EP",
            "20k EP",
        ],
        epic: [
            "Colossal",
            "Semi-Millenium",
            "Triple Nine",
            "Pronic Number",
            "Millenium",
            "Echo",
            "Three Digits",
            "Decay",
            "Framed Quad",
            "Framed Triple",
            "Framed Pair",
            "Contiguous Three Pair",
            "3 Consecutive Numbers(Contains)",
            "Five Of A Kind",
            "Crescendo",
            "Ascension",
            "Zipper",
            "3 Consecutive Numbers(Scrambled)",
            "Tau Slice(4)",
            "E Slice(4)",
            "Pi Slice(4)",
            "Big Brother",
            "8008",
            "Hell",
            "Leet",
            "6767",
            "Deeper Meaning",
            "Very Nice",
            "Jackpot 4",
            "Straight",
            "Strobogrammatic",
            "Deep Void(4)",
            "Contiguous Fives",
            "Three Consecutive Numbers",
            "3rd Power",
            "30k EP",
        ],
        anomaly: [
            "Semi-Epoch",
            "Quad Nine",
            "Epoch",
            "Spy Number",
            "Two Digits",
            "Straight Flush",
            "Binary Soul",
            "Funny Numbers",
            "Homogeneous",
            "4 Consecutive Numbers(Scrambled)",
            "4 Consecutive Numbers(Contains)",
            "Waterfall",
            "4th Power",
            "Fibonacci Number",
            "Cascade",
            "Tau Slice(5)",
            "E Slice(5)",
            "Pi Slice(5)",
            "80085",
            "58008",
            "Royal Flush",
            "Power Of Two",
            "Jackpot Five",
            "Fifth Power",
            "Power Of Three",
            "6th Power",
            "60k EP",
            "100k EP",
        ],
        mythic: [
            "Semi-Eon",
            "Quint Nine",
            "Single Digit",
            "Deep Void(5)",
            "Contiguous Sixes",
            "Eon",
            "Sequence(6)",
            "Hello",
            "Factorial",
            "Power Of Five",
            "Power Of Seven",
            "7th Power",
            "Ouroboros",
            "8th Power",
            "9th Power",
            "4 Consecutive Numbers",
            "Euler's Number",
            "Pi",
            "11th Power",
            "10th Power",
            "Golden Ratio",
            "Tau",
            "19th Power",
            "17th Power",
            "13th Power",
            "Always",
            "Funny Number",
            "Exact Boob",
            "One Million",
            "Full Day",
            "Groundhog Day",
            "Brainrot",
            "Exact Calendar",
            "Exact Orientation",
            "Exact Eighty-Six",
            "Exact Six-Seven",
            "Nine",
            "Eight",
            "Seven",
            "Six",
            "Five",
            "Four",
            "Three",
            "Two",
            "One",
            "Zero",
            "Orwellian",
            "Universal Answer",
            "Mayday",
            "Hotbox",
            "Very Very Nice",
            "17776",
            "Infernal",
            "Not Found",
            "Exact Emergency",
            "Exact Meaning",
            "Exact 80085",
            "Exact Hell",
            "Exact Leet",
            "Exact Devil",
            "Exact Botanist",
            "Jackpot Six",
            "Exact Jackpot",
            "Exact Nice",
            "1M EP",
            "100M EP",
        ],
    }

    for region, location_names in region_location_map.items():
        region.add_locations(get_location_names_with_ids(location_names), RNGdleLocation)

def create_events(world: RNGdleWorld) -> None:
    pass